[[rules]]
id = "ignore-github-secrets"
description = "Ignore GitHub Actions secrets"
regex = '(\${{?\s*secrets\..*}}?)'
tags = ["github-actions"]
allowlist = { paths = [".*\\.ya?ml$"], values = ["SONAR_TOKEN", "ANOTHER_SECRET"] }

[[rules]]
id = "ignore-key-py"
description = "Ignore key.py entirely"
regex = ".*"
tags = ["allowlist"]
allowlist = { paths = ["key.py"], values = [] }

[[rules]]
id = "ignore-dockerfile-secrets"
description = "Ignore secrets in Dockerfile"
regex = ".*"
tags = ["allowlist"]
allowlist = { paths = ["Dockerfile"], values = [] }
