[[rules]]
description = "Ignore GitHub Actions secrets"
regex = '(\${{?\s*secrets\..*}}?)'
tags = ["github-actions"]
allowlist = ["SONAR_TOKEN", "ANOTHER_SECRET"]

[[rules]]
description = "Ignore key.py entirely"
regex = ".*"
allowlist = ["key.py"]
tags = ["allowlist"]
