[[rules]]
description = "Ignore GitHub Actions secrets"
regex = '(\${{?\s*secrets\..*}}?)'
tags = ["github-actions"]
allowlist = { paths = ["<path-to-file-if-needed>"], values = ["SONAR_TOKEN", "ANOTHER_SECRET"] }

[[rules]]
description = "Ignore key.py entirely"
regex = ".*"
tags = ["allowlist"]
allowlist = { paths = ["key.py"], values = [] }  # empty values means ignore everything in the file
