name: Snyk Security Scan

on:
  push:
    branches: [ demo ]
  pull_request:
    branches: [ demo ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.15'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}   # set in GitHub repo secrets
        with:
          args: --file=requirements.txt --package-manager=pip --severity-threshold=high

      # Optional: Upload results as SARIF to GitHub Security tab
      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snyk-reports
          path: |
            snyk-report.json
            snyk-report.html
