name: Snyk Security Scan

on:
  push:
    branches: [ "demo" ]
  pull_request:
    branches: [ "demo" ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.15"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Snyk CLI
        run: |
          npm install -g snyk snyk-to-html

      # Run test - fail build if high/critical vulnerabilities found
      - name: Run Snyk test (fail on high vulns)
        run: |
          snyk test --file=requirements.txt --package-manager=pip \
            --severity-threshold=high \
            --json | snyk-to-html -o snyk-report.html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Upload HTML report as artifact
      - name: Upload Snyk HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.html

      # Monitor - upload snapshot to Snyk UI
      - name: Run Snyk monitor (upload to UI)
        run: |
          snyk monitor --file=requirements.txt --package-manager=pip
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

