name: OWASP ZAP DAST Scan

on:
  workflow_dispatch:   # Trigger manually only 

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start app
        run: |
          python app.py &
          # Wait for the app to be up
          sleep 10
          # Check if app is running
          curl -f http://localhost:5000 || exit 1

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:5000"
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          allow_issue_writing: false
          fail_action: false

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_html.html
            report_json.json
            report_md.md

