name: OWASP ZAP DAST Scan 
  
on: 
   workflow_dispatch:   # Trigger manually 

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start app
        run: |
          pip install -r requirements.txt
          nohup python app.py &
          # Wait for the app to be up
          sleep 5

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:5000"
          format: "html"
          output: "zap-report.html"

      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html

